name: flutter_feather_icons
description: Feather is a collection of simply beautiful open source icons. Each icon is designed on a 24x24 grid with an emphasis on simplicity, consistency and usability. 
version: 2.0.0+1
author: Nikhil Anand <nick.muj.programmer@gmail.com>
homepage: https://github.com/muj-programmer/flutter_feather_icons

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  recase: 4.1.0

flutter:
  fonts:
    - family: FeatherIcons
      fonts:
        - asset: fonts/feather.ttf
